VendeeCrop/Controllers/CropController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VendeeCrop.Models;

namespace VendeeCrop.Controllers
{
    public class CropController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Crop
        public ActionResult Index()
        {
            var cropModels = db.CropModels.Include(c => c.CropType);
            return View(cropModels.ToList());
        }

        // GET: Crop/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropModel cropModel = db.CropModels.Find(id);
            if (cropModel == null)
            {
                return HttpNotFound();
            }
            return View(cropModel);
        }

        // GET: Crop/Create
        public ActionResult Create()
        {
            ViewBag.CropTypeId = new SelectList(db.CropTypeModels, "CropTypeId", "Type");
            return View();
        }

        // POST: Crop/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CropTypeId")] CropModel cropModel)
        {
            if (ModelState.IsValid)
            {
                db.CropModels.Add(cropModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CropTypeId = new SelectList(db.CropTypeModels, "CropTypeId", "Type", cropModel.CropTypeId);
            return View(cropModel);
        }

        // GET: Crop/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropModel cropModel = db.CropModels.Find(id);
            if (cropModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CropTypeId = new SelectList(db.CropTypeModels, "CropTypeId", "Type", cropModel.CropTypeId);
            return View(cropModel);
        }

        // POST: Crop/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CropTypeId")] CropModel cropModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cropModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CropTypeId = new SelectList(db.CropTypeModels, "CropTypeId", "Type", cropModel.CropTypeId);
            return View(cropModel);
        }

        // GET: Crop/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropModel cropModel = db.CropModels.Find(id);
            if (cropModel == null)
            {
                return HttpNotFound();
            }
            return View(cropModel);
        }

        // POST: Crop/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CropModel cropModel = db.CropModels.Find(id);
            db.CropModels.Remove(cropModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VendeeCrop/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1, user-scalable=no, minimal-ui">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="~/signalr/hubs"></script>

</head>
<body class="body-home">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["UserModel"] != null || Request.IsAuthenticated)
                {
                    @Html.ActionLink("Vendee Crop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <a id="amessleft" class="navbar-brand" href="@Url.Action("Messages","Home")"><i id="lblmessage" class="glyphicon glyphicon-envelope"></i><span id="lblMessageCountLeft" class="hidden">0</span></a>
                    <a id="anotileft" class="navbar-brand" href="#"><i id="lblnotification" class="glyphicon glyphicon-bell"></i><span id="lblNotificationCountLeft" class="hidden">0</span></a>
                }
                else
                {
                    @Html.ActionLink("Vendee Crop", "LoginIndex", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["UserModel"] != null)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>

                        if (((VendeeCrop.Models.UserModel)Session["UserModel"]).Type == "Farmer" || Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("My Posts", "Index", "CropPost")</li>
                        }
                    }
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Crops
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Crop List", "Index", "Crop")</li>
                                <li>@Html.ActionLink("Crop Types", "Index", "CropType")</li>
                            </ul>
                        </li>
                        @*<li>@Html.ActionLink("Buyers", "Index", "BuyerModels")</li>*@
                        @*<li>@Html.ActionLink("Farmers", "Index", "FarmerModels")</li>*@
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Users
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Pending For Approval", "ForApproval", "Users")</li>
                                <li><a href="@Url.Action("Index","Users",routeValues: new { id = "Buyer" })">All Buyers</a></li>
                                <li><a href="@Url.Action("Index","Users",routeValues: new { id = "Farmer" })">All Farmers</a></li>
                            </ul>
                        </li>
                        
                        @*<li>@Html.ActionLink("Farmers", "Index", "FarmerModels")</li>*@
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vendee Crop</p>
        </footer>
        @*<input type="hidden" value="" />*@
    </div>




    
    <script type="text/javascript">
        var notificationType = "";
        var fromId = '@(Session["UserModel"] == null ? 0 : (((VendeeCrop.Models.UserModel)Session["UserModel"]).Id))';
        var myUserId = '@(Session["UserModel"] == null ? 0 : (((VendeeCrop.Models.UserModel)Session["UserModel"]).Id))';
        var toId = "";
        var chat;
        var IsOnMessages = false;
        $(function () {
            chat = $.connection.communicationR;
            chat.client.addNewMessageToPage = function (type, from, to, message) {
                //console.log("Type: " + type + ",From: " + from + ",To: " + to + ", Message: " + message);
                
                if (type == "Message") {
                    var unreadMessageCount = parseInt($("#lblMessageCountLeft").html());
                    if (!IsOnMessages) {
                        unreadMessageCount = unreadMessageCount + 1;
                        if (unreadMessageCount > 0) {
                            $("#lblMessageCountLeft").removeClass("hidden");
                            $("#lblMessageCountRight").removeClass("hidden");
                        }
                        $("#lblMessageCountLeft").html(unreadMessageCount);
                        $("#lblMessageCountRight").html(unreadMessageCount);
                        hasnotification = true;
                    } else {
                        MessageReceived(from, to, message);
                        //console.log(!(to != myUserId && from != myUserId))
                        if ((to != myUserId && from != myUserId)) {
                            unreadMessageCount += 1;
                            if (unreadMessageCount > 0) {
                                $("#lblMessageCountLeft").removeClass("hidden");
                                $("#lblMessageCountRight").removeClass("hidden");
                            }
                            $("#lblMessageCountLeft").html(unreadMessageCount);
                            $("#lblMessageCountRight").html(unreadMessageCount);
                            hasnotification = true;
                        }
                    }

                } else if (type == "Notification") {

                }




                //var unreadNotificationCount = parseInt($("#lblNotificationCountLeft").html());
                
                //if (type == "Message") {
                //    //message notification
                //    if ($("#divmessages")) {
                //        MessageReceived(from, to, message);
                //    }
                //}

                //unreadNotificationCount += 1;
                //if (unreadNotificationCount > 0) {
                //    $("#lblNotificationCountLeft").removeClass("hidden");
                //    $("#lblNotificationCountRight").removeClass("hidden");
                //}
                //$("#lblNotificationCountLeft").html(unreadNotificationCount);
                //$("#lblNotificationCountRight").html(unreadNotificationCount);
            }


            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    chat.server.send(notificationType, fromId, toId, $("#myMessage").val());
                });

                function sendrealtime() {
                    chat.server.send(notificationType, fromId, toId, $("#myMessage").val());
                }
            })

            $.ajax({
                url: "/Home/GetMessagesNotificationCount",
                cache: false,
                type: "GET",
                success: function (count) {
                    var unreadMessageCount = parseInt($("#lblMessageCountLeft").html());
                    unreadMessageCount = count;
                    if (unreadMessageCount > 0) {
                        $("#lblMessageCountLeft").removeClass("hidden");
                        $("#lblMessageCountRight").removeClass("hidden");
                    }
                    $("#lblMessageCountLeft").html(unreadMessageCount);
                    $("#lblMessageCountRight").html(unreadMessageCount);
                },
                error: function (request, status, error) {
                    //alert("an error occurred: " + error);
                }
            })



        });



    </script>
</body>
</html>