VendeeCrop/Controllers/CropPostImageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VendeeCrop.Models;

namespace VendeeCrop.Controllers
{
    public class CropPostImageController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CropPostImage
        public ActionResult Index()
        {
            var cropPostImageModels = db.CropPostImageModels.Include(c => c.CropPost);
            return View(cropPostImageModels.ToList());
        }

        // GET: CropPostImage/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropPostImageModel cropPostImageModel = db.CropPostImageModels.Find(id);
            if (cropPostImageModel == null)
            {
                return HttpNotFound();
            }
            return View(cropPostImageModel);
        }

        // GET: CropPostImage/Create
        public ActionResult Create(int id)
        {
            Session["CropPostId"] = id;
            ViewBag.CropPostId = new SelectList(db.CropPostModels, "CropPostId", "Title");
            return View();
        }

        // POST: CropPostImage/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ImageId,ImageName,Image,CropPostId,Created")] CropPostImageModel cropPostImageModel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString("N") + file.FileName;
                    file.SaveAs(HttpContext.Server.MapPath("~/Images/")
                                                          + filename);
                    cropPostImageModel.ImageName = file.FileName;
                    cropPostImageModel.Image = filename;

                    cropPostImageModel.CropPostId = (int)Session["CropPostId"];
                    db.CropPostImageModels.Add(cropPostImageModel);
                    db.SaveChanges();
                    return RedirectToAction("Index","CropPostDetail",new { id = cropPostImageModel.CropPostId});
                }
            }

            ViewBag.CropPostId = new SelectList(db.CropPostModels, "CropPostId", "Title", cropPostImageModel.CropPostId);
            return View(cropPostImageModel);
        }

        // GET: CropPostImage/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropPostImageModel cropPostImageModel = db.CropPostImageModels.Find(id);
            if (cropPostImageModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.CropPostId = new SelectList(db.CropPostModels, "CropPostId", "Title", cropPostImageModel.CropPostId);
            return View(cropPostImageModel);
        }

        // POST: CropPostImage/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ImageId,ImageName,Image,CropPostId,Created")] CropPostImageModel cropPostImageModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cropPostImageModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CropPostId = new SelectList(db.CropPostModels, "CropPostId", "Title", cropPostImageModel.CropPostId);
            return View(cropPostImageModel);
        }

        // GET: CropPostImage/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CropPostImageModel cropPostImageModel = db.CropPostImageModels.Find(id);
            if (cropPostImageModel == null)
            {
                return HttpNotFound();
            }
            return View(cropPostImageModel);
        }

        // POST: CropPostImage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CropPostImageModel cropPostImageModel = db.CropPostImageModels.Find(id);
            db.CropPostImageModels.Remove(cropPostImageModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VendeeCrop/Views/CropPostImage/Create.cshtml
@model VendeeCrop.Models.CropPostImageModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm(Html.BeginForm("Create", "CropPostImage", null, FormMethod.Post,
                                          new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CropPostImageModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="Image" title="Upload an Image" type="file" name="file" />
                
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CropPostId, "CropPostId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CropPostId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CropPostId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VendeeCrop/Views/CropPostImage/Delete.cshtml
@model VendeeCrop.Models.CropPostImageModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CropPostImageModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CropPost.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CropPost.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VendeeCrop/Views/CropPostImage/Details.cshtml
@model VendeeCrop.Models.CropPostImageModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CropPostImageModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CropPost.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CropPost.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ImageId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VendeeCrop/Views/CropPostImage/Edit.cshtml
@model VendeeCrop.Models.CropPostImageModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CropPostImageModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImageId)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CropPostId, "CropPostId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CropPostId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CropPostId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VendeeCrop/Views/CropPostImage/Index.cshtml
@model IEnumerable<VendeeCrop.Models.CropPostImageModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CropPost.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CropPost.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ImageId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ImageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ImageId })
        </td>
    </tr>
}

</table>